# Generated by Django 6.0.5 on 2026-05-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(help_text='Water temperature in °C')),
                ('ph_level', models.FloatField(help_text='Water pH level (0-14)')),
                ('turbidity', models.FloatField(help_text='Water turbidity')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_safe', models.BooleanField(blank=True, help_text='AI Prediction: True=Safe, False=Failure', null=True)),
            ],
        ),
    ]
