# Generated by Django 6.0.5 on 2026-05-21 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_change_requested', models.BooleanField(default=False, help_text='True if the user clicked the manual override button.')),
            ],
        ),
    ]
