# Generated by Django 6.0.5 on 2026-05-28 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_systemconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='node_name',
            field=models.CharField(default='Node A', max_length=20),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='is_safe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='ph_level',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='turbidity',
            field=models.FloatField(),
        ),
    ]
