# Generated by Django 6.0.5 on 2026-09-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_sensorreading_node_name_alter_sensorreading_is_safe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='after_gap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='failure_type',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ph_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='temp_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='turb_delta',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='will_fail_60min',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='is_safe',
            field=models.BooleanField(blank=True, help_text='Verdict of the safety rule at the moment of the reading, not a model prediction.', null=True),
        ),
    ]
